Add support for installing default global npm packages on nvm install
fisherman/fin pull request #179
Opened 2022-03-24 12:21 UTC by kallja

closes #178

2022-05-09 08:42 UTC, smithshelke commented
Until this gets merged, how are you able work around installing global npm packages

2022-05-09 13:56 UTC, jorgebucaran commented
Sorry, I usually never install global packages, but I'd like to see this merged still. It's just that I need a bit of time to sit down and understand what this does and make sure it does it in a way that makes sense. 🙏

2022-06-08 14:58 UTC, jorgebucaran commented on functions/nvm.fish
> +
@kallja What's the purpose of this code?

2022-06-08 15:00 UTC, jorgebucaran requested changes

2022-06-08 15:00 UTC, jorgebucaran commented on functions/nvm.fish
>              end
Think we could boil this down to:

```fish
if set --query nvm_default_packages[1]
    npm install --global $nvm_default_packages
end
```

2022-06-22 15:11 UTC, merged