Fix regex pattern in _nvm_list to correctly match version directory names
fisherman/fin pull request #227
Opened 2024-09-08 16:15 UTC by NV4RE

**Description:**

This PR fixes an issue with the `_nvm_list` function where the regular expression pattern `"v\d.+"` was too broad and could match usernames that contain a `v` followed by digits.

The updated code changes the regular expression pattern to `"/v\d.+"` to match version directory names with a leading slash, and then removes the leading slash from the matched version directory names using `string replace`.

This fix ensures that the `_nvm_list` function correctly matches version directory names and produces the expected output.

**Changes:**

* Updated the regular expression pattern in `_nvm_list` to `"/v\d.+"`
* Added `string replace` to remove the leading slash from matched version directory names

2024-09-08 16:19 UTC, jorgebucaran commented
Extremely helpful and quick turnaround. I'll review this tomorrow, but it looks pretty good. Should we maybe first replace and then match, or am I misreading it?

2024-09-09 03:53 UTC, NV4RE commented
> Extremely helpful and quick turnaround. I'll review this tomorrow, but it looks pretty good. Should we maybe first replace and then match, or am I misreading it?

Updated:

**Changes:**

* Added a new local variable `installed_versions` to store the version directory names without the path
* Used `string replace` to remove the `$nvm_data/` prefix from each version directory name
* Updated the regular expression pattern to match only the version directory names

2024-09-09 10:43 UTC, jorgebucaran requested changes
We should be able to simplify this to:

```fish
set --local versions (string replace --all -- $nvm_data/ "" $nvm_data/*)
```

Could you confirm that works for you and update your commit? I'll merge it once that's done.

2024-09-09 15:16 UTC, NV4RE commented
> We should be able to simplify this to:
> 
> ```fish
> set --local versions (string replace --all -- $nvm_data/ "" $nvm_data/*)
> ```
> 
> Could you confirm that works for you and update your commit? I'll merge it once that's done.

I confirm that simplified change work correctly on my machine

2024-09-09 17:16 UTC, jorgebucaran approved these changes
Let's do this! 👍

2024-09-09 18:00 UTC, merged